version: "3.9"

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "127.0.0.1:8083:3306"
    volumes:
      - ./database_on_local:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    env_file: global_vars.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db